"""Second migration

Revision ID: 06766e4ed307
Revises: b5823b7139d9
Create Date: 2021-04-20 07:22:46.538779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06766e4ed307'
down_revision = 'b5823b7139d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
